; Inno Setup Script for Process Explorer Pro
; Generated by Antigravity

[Setup]
; Unique App ID (Generated for this application)
AppId={{9F82A0F5-A7A2-4D3C-9B6A-01D5C92B4527}
AppName=Process Explorer Pro
AppVersion=1.0.0
AppPublisher=ProcessExplorerPro
DefaultDirName={autopf}\Process Explorer Pro
DefaultGroupName=Process Explorer Pro
AllowNoIcons=yes
; Application icon configuration
SetupIconFile=icons\icon.ico
UninstallDisplayIcon={app}\ProcessExplorerPro.exe
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
OutputDir=setup-output
OutputBaseFilename=ProcessExplorerPro_Setup

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "bin\Release\net9.0-windows\win-x64\publish\ProcessExplorerPro.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Process Explorer Pro"; Filename: "{app}\ProcessExplorerPro.exe"; IconFilename: "{app}\ProcessExplorerPro.exe"
Name: "{group}\{cm:UninstallProgram,Process Explorer Pro}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Process Explorer Pro"; Filename: "{app}\ProcessExplorerPro.exe"; Tasks: desktopicon; IconFilename: "{app}\ProcessExplorerPro.exe"

[Run]
Filename: "{app}\ProcessExplorerPro.exe"; Description: "{cm:LaunchProgram,Process Explorer Pro}"; Flags: nowait postinstall skipifsilent
